[package]
name = "zxrag"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
candle-core = { workspace = true }
candle-examples = { workspace = true }
candle-nn = { workspace = true }
candle-transformers = { workspace = true }
clap = { workspace = true }
tokenizers = { workspace = true, features = ["onig"] }
tracing-subscriber = { workspace = true }
tracing-chrome = { workspace = true }
hf-hub = { workspace = true }
serde_json = { workspace = true }
